<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ParqueoCarga.DbModel\ParqueoCarga.DbModel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cbaca439-a316-4677-a9e1-521be1efdb11</UserSecretsId>
  </PropertyGroup>

</Project>
